<script setup lang="ts">
import type { IDatasheetWeapon } from '@/types/datasheets'

const props = defineProps<{ modelValue: IDatasheetWeapon }>()
const emit = defineEmits(['update:modelValue', 'addWeapon', 'deleteWeapon'])

const updateAttribute = (updatedAttr: Object) => {
  emit('update:modelValue', {
    ...props.modelValue,
    attributes: {
      ...props.modelValue.attributes,
      ...updatedAttr
    }
  })
}

const addWeapon = () => emit('addWeapon')
const deleteWeapon = () => emit('deleteWeapon')

// TODO: This should be generated by examining the type
const attributes = [
  'range',
  'attacks',
  'skill',
  'strength',
  'armour_penetration',
  'damage'
]
</script>
<template>
  <tr>
    <td>
      <input
        class="input"
        :value="modelValue.name"
        @input="
          $emit('update:modelValue', {
            ...modelValue,
            name: ($event.target as HTMLInputElement).value
          })
        "
      />
    </td>
    <td
      v-for="attribute in attributes"
      :key="attribute"
      class="create-weapon-row__centered-col"
    >
      <input
        class="input create-weapon-row__attribute-input"
        :value="(modelValue.attributes as any)[attribute]"
        @input="
          updateAttribute({
            [attribute]: ($event.target as HTMLInputElement).value
          })
        "
      />
    </td>
    <td>
      <button type="button" @click="addWeapon">+</button>
      <button type="button" @click="deleteWeapon">-</button>
    </td>
  </tr>
</template>
<style scoped lang="scss">
.create-weapon-row__centered-col {
  text-align: center;
}
.create-weapon-row__attribute-input {
  max-width: 1.5rem;
  align-self: center;
  text-align: center;
}
</style>
